### ISSUE TITLE
Description of tool usage is not correct

### ISSUE THREAD

**Issue by alexpeleg** [rotemreiss/robusto#1]
In order to run the tool, you can type:
 ./robusto domain.com
other methods which are supported by subfinder are not supported

**Comment by rotemreiss** [comment]
Hi @alexpeleg ,

Thanks for reaching out!

The correct usage is as described in the readme.
In the initial version, it was like you mentioned, but now it should work as documented, e.g.:
`echo "domain.com" > ./robusto.sh` for a single domain.

Try to pull the latest version using `git pull origin master` and retry.

Thanks.

**Comment by rotemreiss** [comment]
After rechecking you were right, I wrote `>` instead of `|`.
Fixed in https://github.com/rotemreiss/robusto/commit/36c4119eb504562a6e54174927a5363a0ed0bb9f .

Thanks!
